version: '2'
services:
  xarmat-app:
    image: xarmat
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://xarmat-postgresql:5432/Xarmat
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  xarmat-postgresql:
    extends:
      file: postgresql.yml
      service: xarmat-postgresql
